version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node-browsers
    steps:
      - checkout
      - run: npm ci
      - run:
          name: "Building frontend"
          command: "npx shadow-cljs release app"
  test-frontend:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node-browsers
    steps:
      - checkout
      - run: npm ci
      - run:
          name: "Testing frontend"
          command: npm test
  lint:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node-browsers
    steps:
      - checkout
      - run:
          name: "Install clj-kondo"
          command: "curl -sO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo && chmod +x install-clj-kondo && ./install-clj-kondo"
      - run:
          name: "Run clj-kondo"
          command: clj-kondo --lint src

workflows:
  version: 2
  build-and-test:
    jobs:
    - build-frontend
    - test-frontend
    - lint